spring:
  data:
    mongodb:
      username: abdel
      password: abdel@2211
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090